# Generated by Django 2.1.3 on 2019-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('nickName', models.CharField(max_length=20)),
                ('isNotice', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
