# Generated by Django 2.1.3 on 2019-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
