# Generated by Django 2.1.3 on 2019-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseApp', '0002_auto_20190725_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='isNotice',
            field=models.BooleanField(null=True),
        ),
    ]
