# Generated by Django 2.1.3 on 2019-07-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChineseApp', '0003_auto_20190725_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
